version: '3'

networks:
  inception-network:
    name: inception-network
    driver: bridge


volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      o: bind
      type: none
      device: /home/jkarosas/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      o: bind
      type: none
      device: /home/jkarosas/data/mariadb


services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception-network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/
    networks:
      - inception-network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress  
    volumes:
      - ./requirements/nginx/tools/nginx.conf:/etc/nginx/sites-enabled/default
      - ${CERTS}/jkarosas.42.fr.crt:/etc/nginx/ssl/jkarosas.42.fr.crt
      - ${CERTS}/jkarosas.42.fr.key:/etc/nginx/ssl/jkarosas.42.fr.key
      - wp:/var/www/
    networks:
      - inception-network
    restart: always
  
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always
  
  website:
    container_name: website
    build: ./requirements/bonus/website
    ports:
      - "8081:80"
    restart: always